---
- name: Run commands before repo setup
  shell: >
    set -o pipefail &&
    {{ repo_setup_dir }}/{{ repo_cmd_before_setup_script }} 2>&1 {{ timestamper_cmd }}
    | tee -a {{ repo_setup_dir }}/{{ repo_setup_log }}
  become: true
  register: result
  changed_when: true

- name: Setup repos on live host
  shell: >
    set -o pipefail &&
    {{ repo_setup_dir }}/{{ repo_setup_new_script }} 2>&1 {{ timestamper_cmd }}
    | tee -a {{ repo_setup_dir }}/{{ repo_setup_log }}
  become: true
  register: result
  changed_when: true

- include_tasks: yum-config-generic.yml

- include_tasks: yum-config-compose.yml

- name: Run commands after repo setup
  shell: >
    set -o pipefail &&
    {{ repo_setup_dir }}/{{ repo_cmd_after_setup_script }} 2>&1 {{ timestamper_cmd }}
    | tee -a {{ repo_setup_dir }}/{{ repo_setup_log }}
  become: true
  register: result
  changed_when: true
